In [1]:
#Q(1):multiplication of 2 given matrixes
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[4, 5], [6, 7]])
m = np.dot(m1, m2)
print(m)

[[16 19]
 [36 43]]


In [2]:
#Q(2):outer product of 2 given vectors
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[4, 5], [6, 7]])
m = np.outer(m1, m2)
print(m)

[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]
 [16 20 24 28]]


In [3]:
#Q(3):cross product of 2 given vectors
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[4, 5], [6, 7]])
m = np.cross(m1, m2)
print(m)

[-3 -3]


In [9]:
#Q(4):determinant of a given square array
import numpy as np
m1 = np.array([[4, 5], [6, 7]])
m = np.linalg.det(m1)
print(m)

-2.0000000000000013


In [12]:
#Q(5):Einstein's summation convention of two given multidimensional arrays
import numpy as np
m1 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
m2 = np.array([[3, 4, 5], [6, 7, 8], [9, 10, 11]])
m = np.einsum("mk, kn", m1, m2)
print(m)

[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


In [13]:
#Q(6):inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension
import numpy as np
m1 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
m2 = np.array([[3, 4, 5], [6, 7, 8], [9, 10, 11]])
m = np.inner(m1, m2)
print(m)

[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


In [14]:
#Q(7):eigenvalues and right eigenvectors of a given square array
import numpy as np
m1 = np.array([[3, -2], [1, 0]])
m, n = np.linalg.eig(m1)
print(m)
print(n)

[2. 1.]
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [15]:
#Q(8):Kronecker product of two given mulitdimension arrays
import numpy as np
m1 = np.array([1, 2, 3])
m2 = np.array([0, 1, 0])
m = np.kron(m1, m2)
print(m)

[0 1 0 0 2 0 0 3 0]


In [16]:
#Q(9):condition number of a given matrix
import numpy as np
m1 = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
m = np.linalg.cond(m1)
print(m)

1.4142135623730951


In [17]:
#Q(10):find a matrix or vector norm
import numpy as np
m1 = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
m = np.linalg.norm(m1)
print(m)

2.23606797749979


In [18]:
#Q(11):compute the determinant of an array
import numpy as np
m1 = np.array([[1,2],[3,4]])
m = np.linalg.det(m1)
print(m)

-2.0000000000000004


In [19]:
#Q(12):compute the inverse of a given matrix
import numpy as np
m1 = np.array([[1,2],[3,4]])
m = np.linalg.inv(m1)
print(m)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
#Q(13):calculate the QR decomposition of a given matrix
import numpy as np
m1 = np.array([[1,2],[3,4]])
m = np.linalg.qr(m1)
print(m)

(array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


In [21]:
#Q(14):compute the condition number of a given matrix
import numpy as np
m1 = np.array([[1,2],[3,4]])
m = np.linalg.cond(m1)
print(m)

14.933034373659265


In [22]:
#Q(15):compute the sum of the diagonal element of a given array
import numpy as np
m1 = np.array([[0, 1, 2], [3, 4, 5]])
m = np.trace(m1)
print(m)

4
